lang: vi-VN
title: My Blog
email: ntngocwd@gmail.com
description: My personal blog about everything I have learned
# author:
#   name: Nguyen Thai Ngoc
#   picture: https://res.cloudinary.com/ntngoc96/image/upload/v1678503088/Personal%20Info/avatar_p5dgxx.jpg
github_username: nntwelve
theme: minima
# theme: jekyll-theme-basically-basic
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
